### ISSUE TITLE
Skip first X lines, or skip last X lines, for table headers/footers

### ISSUE THREAD

**Issue by Krellan** [google/keep-sorted#17]
Thought of a feature request.

Would be nice to have an option to skip the first X lines, to preserve an unsorted header, such as a Markdown table in which you need to preserve the first 2 lines and keep them unsorted.

For symmetry, also have an option to skip the last X lines, similarly.

Any thoughts on this? Thanks!

**Comment by JeffFaer** [comment]
Do you have an example of what you're describing that I could take a look at?

**Comment by Krellan** [comment]
Glad you asked. Here's Markdown.



Name | Value
---- | ----
Alpha|Foo
Bravo|Bar
Charlie | Baz
Delta|Qux


The objective is to avoid wrongly sorting the header row and the divdier row (between the header and the content), while making sure the content itself (all following lines) remains sorted.

**Comment by JeffFaer** [comment]
Ah okay, and putting the comment in the correct place without the skip-first directive breaks markdown formatting:

```
<!-- Example to want to avoid sorting the first two lines -->
Name | Value
---- | ----
<!-- keep-sorted start -->
Alpha|Foo
Bravo|Bar
Charlie | Baz
Delta|Qux
<!-- keep-sorted end -->
```


Name | Value
---- | ----

Alpha|Foo
Bravo|Bar
Charlie | Baz
Delta|Qux


----

keep-sorted doesn't actually require that its start directive be on its own line, but that also breaks markdown formatting:

```
<!-- Example to want to avoid sorting the first two lines -->
Name | Value
---- | ---- <!-- keep-sorted start -->
Alpha|Foo
Bravo|Bar
Charlie | Baz
Delta|Qux
<!-- keep-sorted end -->
```


Name | Value
---- | ---- 
Alpha|Foo
Bravo|Bar
Charlie | Baz
Delta|Qux


----

This seems like reasonable functionality to add to keep-sorted

**Comment by Krellan** [comment]
Yep, you got it! That's exactly the use case. Thanks for taking a look at it.
